# Generated by Django 4.0.3 on 2022-03-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdmadeapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
