# Generated by Django 4.0.3 on 2022-03-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdmadeapp', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('new', 'New'), ('on sale', 'On sale'), ('fall collection', 'Fall Collection')], max_length=1024)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='crowdmadeapp.product')),
            ],
        ),
    ]
